In [14]:
import tushare as ts
import pandas as pd

TOKEN = "3e61ce5a2689d5f97b8187798a02a7d15827726acc117574773616bf"
ts.set_token(TOKEN)
pro = ts.pro_api()

df = pro.income(ts_code='000001.SZ', start_date='20180101', end_date='20181231', fields='ann_date,f_ann_date,end_date,basic_eps')

In [15]:
df

   ann_date f_ann_date  end_date  basic_eps
0  20181024   20181024  20180930       1.14
1  20180816   20180816  20180630       0.73
2  20180816   20180816  20180630       0.73
3  20180420   20180420  20180331       0.33
4  20180420   20180420  20180331       0.33
5  20180315   20180315  20171231       1.30
6  20180315   20180315  20171231       1.30

In [ ]:
import os
import tushare as ts
pro = ts.pro_api('668abb29cc52a8705de90c196e965520e4cd6851c65f0c373e4d4c46')
pro._DataApi__http_url = "https://tx.xiaodefa.top/"
df = pro.index_basic(limit=5)
# # pro_bar接口请加上api=pro
# df = ts.pro_bar(api=pro, ts_code="000001.SZ", limit=3)
# print(df)
df1 = pro.income_vip(start_date='20240101', end_date='20240630',report_type=5, fields='ts_code,ann_date,f_ann_date,end_date,basic_eps')

df1

       ts_code  ann_date f_ann_date  end_date  basic_eps
0    301099.SZ  20240423   20240423  20240331       0.33
1    920405.BJ  20240427   20240427  20240331       0.21
2    600732.SH  20240427   20240427  20240331      -0.05
3    688388.SH  20240425   20240425  20240331      -0.11
4    002849.SZ  20240425   20240425  20240331       0.17
..         ...       ...        ...       ...        ...
258  874125.BJ  20240206   20240206  20221231       2.19
259  874476.BJ  20240627   20240627  20221231       0.66
260  874392.BJ  20240127   20240127  20221231       0.34
261  874475.BJ  20240629   20240629  20221231       1.37
262  301275.SZ  20240606   20240606  20211231      -0.02

[263 rows x 5 columns]

In [ ]:
import os
import tushare as ts
pro = ts.pro_api('668abb29cc52a8705de90c196e965520e4cd6851c65f0c373e4d4c46')
pro._DataApi__http_url = "https://tx.xiaodefa.top/"
df = pro.index_basic(limit=5)
# # pro_bar接口请加上api=pro
# df = ts.pro_bar(api=pro, ts_code="000001.SZ", limit=3)
# print(df)

codes = ','.join(df1['ts_code'].tolist())

df2 = pro.income_vip(ts_code = codes, start_date='20240101', end_date='20240630',report_type=1, fields='ts_code,ann_date,f_ann_date,end_date,basic_eps')

df2

       ts_code  ann_date f_ann_date  end_date  basic_eps
0    873669.BJ  20240528   20240528  20240331     0.2700
1    300959.SZ  20240424   20240424  20240331    -0.0500
2    873911.BJ  20240608   20240608  20240331     0.0600
3    301099.SZ  20240423   20240626  20240331     0.2300
4    301152.SZ  20240430   20240430  20240331    -0.3800
..         ...       ...        ...       ...        ...
521  874476.BJ  20240627   20241231  20221231     0.6500
522  874194.BJ  20240522   20241207  20221231     0.7287
523  874194.BJ  20240522   20250719  20221231     0.7287
524  688691.SH  20240321   20240321  20221231     1.0500
525  874378.BJ  20240613   20250313  20211231     0.0900

[526 rows x 5 columns]

In [60]:
df1.sort_values('ts_code')

       ts_code  ann_date f_ann_date  end_date  basic_eps
157  000422.SZ  20240413   20240413  20231231     0.4698
148  000505.SZ  20240330   20240330  20231231     0.1400
114  000506.SZ  20240430   20240430  20231231     0.0300
112  000547.SZ  20240430   20240430  20231231    -1.2200
94   000559.SZ  20240430   20240430  20231231     0.2500
..         ...       ...        ...       ...        ...
242  920932.BJ  20240423   20240423  20231231     0.7600
248  920932.BJ  20240423   20240423  20231231     0.7600
216  920974.BJ  20240426   20240426  20231231     0.0300
205  920974.BJ  20240426   20240426  20231231     0.0300
89   920985.BJ  20240430   20240430  20231231     0.4400

[263 rows x 5 columns]

In [59]:
df2.sort_values('ts_code')

       ts_code  ann_date f_ann_date  end_date  basic_eps
396  000422.SZ  20240413   20250403  20231231     0.4698
195  000422.SZ  20240427   20240427  20240331     0.1293
429  000422.SZ  20240413   20240413  20231231     0.4698
175  000505.SZ  20240425   20240425  20240331     0.0300
394  000505.SZ  20240330   20251018  20231231     0.1400
..         ...       ...        ...       ...        ...
198  920974.BJ  20240426   20240829  20231231     0.0700
177  920974.BJ  20240426   20240426  20240331     0.0500
217  920985.BJ  20240430   20260228  20231231     0.4400
215  920985.BJ  20240430   20240430  20231231     0.4400
108  920985.BJ  20240430   20240430  20240331     0.0600

[526 rows x 5 columns]

In [54]:
mask = (pd.to_datetime(df2['f_ann_date']) - pd.to_datetime(df2['ann_date'])) > pd.Timedelta(0,'days')
df2[mask]

        ts_code  ann_date f_ann_date  end_date  basic_eps
668   300087.SZ  20240425   20260130  20240331     0.0100
890   601608.SH  20240426   20240514  20240331     0.0207
1457  603156.SH  20240424   20240910  20240331     0.6946
1475  688287.SH  20240430   20241026  20240331    -0.0200
1888  300536.SZ  20240429   20240828  20240331     0.0458
...         ...       ...        ...       ...        ...
8945  600252.SH  20240330   20260321  20231231     0.0246
8953  874399.BJ  20240330   20240628  20231231     0.4400
8960  000505.SZ  20240330   20251018  20231231     0.1400
8969  688270.SH  20240330   20251225  20231231     0.4700
8976  874280.BJ  20240330   20240627  20231231     1.4400

[85 rows x 5 columns]

In [63]:
df = pro.ci_index_member(is_new='N',fields='l1_name,ts_code,name,in_date,out_date')
df

      l1_name    ts_code      name   in_date  out_date
0          综合  000732.SZ  ST泰禾(退市)  20030101  20120902
1     电力及公用事业  000005.SZ  ST星源(退市)  20180227  20191201
2         房地产  000005.SZ  ST星源(退市)  20030101  20180226
3          汽车  600565.SH  ST迪马(退市)  20030101  20140430
4          电子  002341.SZ  ST新纶(退市)  20100205  20191201
...       ...        ...       ...       ...       ...
2943     综合金融  600599.SH      退市熊猫  20191202  20221212
2944       医药  600421.SH      退市华嵘  20040621  20150430
2945     基础化工  600636.SH      退市国化  20030101  20191201
2946      房地产  600696.SH      退市岩石  20030101  20200529
2947    非银行金融  600599.SH      退市熊猫  20170301  20191201

[2948 rows x 5 columns]

In [71]:
df = pro.balancesheet_vip(ts_code = '000001.SZ', start_date='20180101', end_date='20190730', fields='ts_code,ann_date,f_ann_date,end_date,report_type,comp_type,cap_rese,update_flag').sort_values('ts_code')

In [73]:
df.sort_values('end_date')

,ts_code,ann_date,f_ann_date,end_date,report_type,comp_type,cap_rese,update_flag
8,000001.SZ,20180315,20180315,20171231,1,2,5.646500e+10,0
9,000001.SZ,20180315,20180315,20171231,1,2,5.646500e+10,1
7,000001.SZ,20180420,20180420,20180331,1,2,5.646500e+10,0
5,000001.SZ,20180816,20180816,20180630,1,2,5.646500e+10,0
6,000001.SZ,20180816,20180816,20180630,1,2,5.646500e+10,1
3,000001.SZ,20181024,20181024,20180930,1,2,5.646500e+10,0
4,000001.SZ,20181024,20181024,20180930,1,2,5.646500e+10,1
1,000001.SZ,20190307,20190307,20181231,1,2,5.646500e+10,0
2,000001.SZ,20190307,20190307,20181231,1,2,5.646500e+10,1
0,000001.SZ,20190424,20190424,20190331,1,2,5.646500e+10,1

In [76]:
df = pro.fina_indicator_vip(fields='ts_code,ann_date,f_ann_date,end_date,op_to_ebt')
df

       ann_date  end_date  op_to_ebt    ts_code
0      20260606  20260331    99.6646  920117.BJ
1      20260703  20260331   100.0002  874571.BJ
2      20260522  20260331        NaN  688806.SH
3      20260701  20260331        NaN  A25079.SH
4      20260613  20260331    98.0787  874390.BJ
...         ...       ...        ...        ...
11995  20260417  20251231   100.1278  603338.SH
11996  20260417  20251231   100.3473  300160.SZ
11997  20260417  20251231    99.5957  603496.SH
11998  20260417  20251231   100.5465  920478.BJ
11999  20260417  20251231        NaN  688296.SH

[12000 rows x 4 columns]

In [80]:
TOKEN = "3e61ce5a2689d5f97b8187798a02a7d15827726acc117574773616bf"
ts.set_token(TOKEN)
pro = ts.pro_api()

df = pro.fina_mainbz(ts_code='000627.SZ', fields='ts_code,end_date,update_flag')

In [81]:
df

       ts_code  end_date update_flag
0    000627.SZ  20240630           0
1    000627.SZ  20240630           0
2    000627.SZ  20240630           0
3    000627.SZ  20240630           0
4    000627.SZ  20240630           0
..         ...       ...         ...
145  000627.SZ  20160630           1
146  000627.SZ  20160630           1
147  000627.SZ  20160630           0
148  000627.SZ  20160630           1
149  000627.SZ  20160630           1

[150 rows x 3 columns]

In [91]:
TOKEN = "3e61ce5a2689d5f97b8187798a02a7d15827726acc117574773616bf"
ts.set_token(TOKEN)
pro = ts.pro_api()

df = pro.stk_holdernumber(ts_code='000001.SZ', start_date='20240101', end_date='20240531').sort_values('ann_date')
df

     ts_code  ann_date  end_date  holder_num
2  000001.SZ  20240315  20240229      566200
4  000001.SZ  20240315  20231231      573282
3  000001.SZ  20240322  20240228      566200
0  000001.SZ  20240420  20240331      567902
1  000001.SZ  20240522  20240329      567902

In [3]:
import tushare as ts

TOKEN = "aec43dc2cba51952f47ca1bfba90e905264a7a11777f17af356ace45"
ts.set_token(TOKEN)
pro = ts.pro_api()

df = pro.stk_holdernumber(ts_code='000001.SZ', start_date='20240101', end_date='20240531').sort_values('ann_date')
df

Exception: 您的token不对，请确认。